  - name: install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: add docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Install docker packages
    ansible.builtin.yum:
      name: "{{ item }}"
      state: latest
    with_items:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-buildx-plugin
       - docker-compose-plugin

  - name: copy docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64"
      dest: /usr/local/bin/docker-compose

  - name: chmod docker-compose
    shell: |
            chmod +x /usr/local/bin/docker-compose
            ln -s /usr/local/bin/docker-compose /usr/bin/

  - name: start and enable docker
    systemd:
      name: docker
      enabled: yes
      state: started
